name: parallel
on:
  workflow_dispatch:
jobs:
  parallel-demo1:
    runs-on: ubuntu-latest 
    steps:
      - name: job1
        run: echo "this is job-1"
  
  parallel-demo2:
    runs-on: ubuntu-latest
    steps:
      - name: job2 
        run: echo " this is job-2"

  parallel-demo3:
    runs-on: ubuntu-latest
    steps:
      - name: job3
        run: echo " this is job-3"

  parallel-demo4:
    runs-on: ubuntu-latest
    steps:
      - name: job4
        run: echo " this is job-4"