name: checkout-demo
on: workflow_dispatch 
jobs:
  checkout-sample:
  runs-on: ubuntu-latest 
    - name: checkout repository
      uses: actions/checkout@v6

    - name: see the sample content
      run: cat sample.txt
       