name: Testing Workflow
on: workflow_dispatch 
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Hello Display
              run: echo "welcome to GA"
            - name: Display the date
              run: date