name: File Provisioners in GIT_HUB

on: workflow_dispatch

jobs:
    demo_workflows:
        runs-on: ubuntu-latest
        steps:
            - name: say Hello
              run: echo "hello github_actions" > demo.txt
            - name: see the content in file
              run: cat demo.txt
            - name: show the date
              run: date
            - name: see the files and directories
              run: ls -ltrh
            - name: know the present working directory
              run: pwd
